<a href="https://colab.research.google.com/github/rijulsharma/10-Days-of-Data-Science-and-ML/blob/master/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mpt 
import sklearn.preprocessing

In [56]:
df=pd.read_csv("https://raw.githubusercontent.com/patilankita79/ML_DataPreprocessing/master/ML_DataPreprocessing/Data.csv")

In [57]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [58]:
x= df.iloc[:,:-1].values 
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [59]:
y= df.iloc[:,3].values 
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [60]:
from sklearn.impute import SimpleImputer  
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(x[:,1:3])
x[:, 1:3]= imr.transform(x[:, 1:3]) 
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [61]:
from sklearn.preprocessing import LabelEncoder  
label_encoder_x= LabelEncoder()  
x[:, 0]= label_encoder_x.fit_transform(x[:, 0])
x  

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [62]:
labelencoder_y= LabelEncoder()  
y= labelencoder_y.fit_transform(y)  
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [63]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  

In [64]:
print(x_train)

[[1 40.0 63777.77777777778]
 [0 37.0 67000.0]
 [2 27.0 48000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [2 38.0 61000.0]
 [0 44.0 72000.0]
 [0 35.0 58000.0]]


In [65]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    

In [66]:
print(x_train)

[[ 0.13483997  0.26306757  0.12381479]
 [-0.94387981 -0.25350148  0.46175632]
 [ 1.21355975 -1.97539832 -1.53093341]
 [ 1.21355975  0.05261351 -1.11141978]
 [-0.94387981  1.64058505  1.7202972 ]
 [ 1.21355975 -0.0813118  -0.16751412]
 [-0.94387981  0.95182631  0.98614835]
 [-0.94387981 -0.59788085 -0.48214934]]


In [67]:
x_test= st_x.transform(x_test)  

In [68]:
print(x_test)

[[ 0.13483997 -1.45882927 -0.90166297]
 [ 0.13483997  1.98496442  2.13981082]]
