<a href="https://colab.research.google.com/github/rijulsharma/10-Days-of-Data-Science-and-ML/blob/master/Movie_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import *
num_movies=10
num_users=5
ratings= random.randint(11,size=(num_movies,num_users)) 
print(ratings)

[[ 2 10  7  9  9]
 [10  2  7  5  0]
 [ 3  8  4  4  2]
 [10  7  4  8  5]
 [ 7  8  3  5  2]
 [ 4  2  0  9 10]
 [ 1  7  3  2  2]
 [ 8 10  7  1  7]
 [ 3  9  6  9  8]
 [ 2  2  3  8  7]]


In [ ]:
did_rate=(ratings!=0)*1
print(did_rate)

[[1 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
rijul_ratings=zeros((num_movies,1))
print(rijul_ratings)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
rijul_ratings[0]=8
rijul_ratings[2]=7
rijul_ratings[4]=3
print(rijul_ratings)

[[8.]
 [0.]
 [7.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [ ]:
ratings=append(rijul_ratings,ratings,axis=1)
did_rate=append(((rijul_ratings!=0)*1),did_rate,axis=1)
print(ratings)
print(did_rate)

[[ 8.  2. 10.  7.  9.  9.]
 [ 0. 10.  2.  7.  5.  0.]
 [ 7.  3.  8.  4.  4.  2.]
 [ 0. 10.  7.  4.  8.  5.]
 [ 3.  7.  8.  3.  5.  2.]
 [ 0.  4.  2.  0.  9. 10.]
 [ 0.  1.  7.  3.  2.  2.]
 [ 0.  8. 10.  7.  1.  7.]
 [ 0.  3.  9.  6.  9.  8.]
 [ 0.  2.  2.  3.  8.  7.]]
[[1 1 1 1 1 1]
 [0 1 1 1 1 0]
 [1 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 1 1 0 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]]


In [ ]:
def normalize_ratings(ratings,did_rate):
  num_movies=ratings.shape[0]

  ratings_mean=zeros(shape=(num_movies,1))
  ratings_norm=zeros(shape=ratings.shape)

  for i in range (num_movies):
    idx=where(did_rate[i]==1)[0]
    ratings_mean[i]=mean(ratings[i,idx])
    ratings_norm[i,idx]=ratings[i,idx]-ratings_mean[i]
  return ratings_norm,ratings_mean


In [ ]:
ratings,ratings_mean=normalize_ratings(ratings,did_rate)
print (ratings)

[[ 0.5        -5.5         2.5        -0.5         1.5         1.5       ]
 [ 0.          4.         -4.          1.         -1.          0.        ]
 [ 2.33333333 -1.66666667  3.33333333 -0.66666667 -0.66666667 -2.66666667]
 [ 0.          3.2         0.2        -2.8         1.2        -1.8       ]
 [-1.66666667  2.33333333  3.33333333 -1.66666667  0.33333333 -2.66666667]
 [ 0.         -2.25       -4.25        0.          2.75        3.75      ]
 [ 0.         -2.          4.          0.         -1.         -1.        ]
 [ 0.          1.4         3.4         0.4        -5.6         0.4       ]
 [ 0.         -4.          2.         -1.          2.          1.        ]
 [ 0.         -2.4        -2.4        -1.4         3.6         2.6       ]]


In [ ]:
print(ratings_mean)

[[7.5       ]
 [6.        ]
 [4.66666667]
 [6.8       ]
 [4.66666667]
 [6.25      ]
 [3.        ]
 [6.6       ]
 [7.        ]
 [4.4       ]]


In [ ]:
num_users=ratings.shape[1]
num_features=3


In [ ]:
movie_features=random.randn(num_movies,num_features)
user_prefs=random.randn(num_users,num_features)
intial_X_and_theta= r_[movie_features.T.flatten(),user_prefs.T.flatten()]
print(movie_features)

                            

[[ 1.68439184  0.06333963  0.38960823]
 [-1.82793848 -1.19487785 -0.08777884]
 [ 0.49049455  0.42250431 -0.70445626]
 [-0.81500182  0.67370502  0.36247413]
 [-0.44073656  0.47747894 -0.28558238]
 [-1.31966774  0.23641354 -0.73025547]
 [-1.14598422 -0.47478768 -1.33300251]
 [-0.96059131 -0.97602971  1.45971947]
 [-0.17298372 -1.54255178 -0.11566443]
 [-0.46836611 -0.36224871 -0.10419908]]


In [ ]:
print(user_prefs)

[[-0.03000819 -0.52683725  0.17767052]
 [ 1.56633173  1.20557929  0.12516324]
 [-0.94661597  0.64132909  1.2486581 ]
 [-0.45522706  0.32248979 -0.05104432]
 [-0.69542683 -0.90624151  0.57873431]
 [-0.79010865  0.59518858 -1.86392363]]


In [ ]:
print(intial_X_and_theta)

[ 1.68439184 -1.82793848  0.49049455 -0.81500182 -0.44073656 -1.31966774
 -1.14598422 -0.96059131 -0.17298372 -0.46836611  0.06333963 -1.19487785
  0.42250431  0.67370502  0.47747894  0.23641354 -0.47478768 -0.97602971
 -1.54255178 -0.36224871  0.38960823 -0.08777884 -0.70445626  0.36247413
 -0.28558238 -0.73025547 -1.33300251  1.45971947 -0.11566443 -0.10419908
 -0.03000819  1.56633173 -0.94661597 -0.45522706 -0.69542683 -0.79010865
 -0.52683725  1.20557929  0.64132909  0.32248979 -0.90624151  0.59518858
  0.17767052  0.12516324  1.2486581  -0.05104432  0.57873431 -1.86392363]


In [ ]:
def unroll_params(X_and_theta,num_users,num_movies,num_features):
  first_30=X_and_theta[:num_movies*num_features]
  X=first_30.reshape((num_features,num_movies)).transpose()
  last_18=X_and_theta[num_movies*num_features:]
  theta=last_18.reshape(num_features,num_users).transpose()
  return X, theta 

In [ ]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	
	difference = X.dot( theta.T ) * did_rate - ratings
	X_grad = difference.dot( theta ) + reg_param * X
	theta_grad = difference.T.dot( X ) + reg_param * theta
	
	 
	return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [ ]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
	X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
	
	
	cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2

	regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
	return cost + regularization


In [ ]:
from scipy import optimize
reg_param = 30
minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=intial_X_and_theta,args=(ratings, did_rate, num_users, num_movies, num_features, reg_param),maxiter=100, disp=True, full_output=True)
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]

Optimization terminated successfully.
         Current function value: 163.058333
         Iterations: 10
         Function evaluations: 22
         Gradient evaluations: 22


In [ ]:
print (movie_features)

[[ 1.68439184  0.06333963  0.38960823]
 [-1.82793848 -1.19487785 -0.08777884]
 [ 0.49049455  0.42250431 -0.70445626]
 [-0.81500182  0.67370502  0.36247413]
 [-0.44073656  0.47747894 -0.28558238]
 [-1.31966774  0.23641354 -0.73025547]
 [-1.14598422 -0.47478768 -1.33300251]
 [-0.96059131 -0.97602971  1.45971947]
 [-0.17298372 -1.54255178 -0.11566443]
 [-0.46836611 -0.36224871 -0.10419908]]


In [ ]:
print (user_prefs)

[[-0.03000819 -0.52683725  0.17767052]
 [ 1.56633173  1.20557929  0.12516324]
 [-0.94661597  0.64132909  1.2486581 ]
 [-0.45522706  0.32248979 -0.05104432]
 [-0.69542683 -0.90624151  0.57873431]
 [-0.79010865  0.59518858 -1.86392363]]


In [ ]:
all_predictions = movie_features.dot( user_prefs.T )
print(all_predictions)

[[-0.01469332  2.76344196 -1.0673632  -0.76624165 -1.00329263 -2.01935353]
 [ 0.66876356 -4.3146647   0.85444007  0.45127177  2.30324473  0.89670541]
 [-0.36247097  1.18946759 -1.07297068 -0.05107458 -1.13168701  1.17697842]
 [-0.26607521 -0.41898995  1.65616663  0.56977163  0.16601089  0.36929742]
 [-0.28906756 -0.15044535  0.36683465  0.36919465 -0.29148752  1.16472352]
 [-0.21469549 -1.87342332  0.48899803  0.71426481  0.2808607   2.54453195]
 [ 0.04768949 -2.53422854 -0.88415257  0.43661105  0.45576619  3.10747872]
 [ 0.80238353 -2.49858264  2.10604536  0.04801716  2.39732934 -2.54275585]
 [ 0.7973145  -2.1450953  -0.96995951 -0.41280631  1.451283   -0.56584361]
 [ 0.18638783 -1.18337813  0.08093319  0.10171019  0.59369559  0.34867294]]


In [ ]:
predictions_for_rijul = all_predictions[:, 0:1] + ratings_mean
print (predictions_for_rijul)


In [ ]:
print (rijul_ratings)

[[8.]
 [0.]
 [7.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
